# One-Hot Encoding

```{r}
mr=read.csv("mushroom.csv",header=F);head(mr)
```

```{r}
for(i in 1:23){
  mr[,i]=as.factor(mr[,i])
}
head(mr)
```

```{r}
for(i in 2:23){
  mr[,i]=as.numeric(mr[,i])
}
head(mr)
```

## One-Hot Encoding

각 컬럼별 데이터 확인

```{r}
for(i in 2:23){
  cat("column: ",colnames(mr)[i])
  print(table(mr[,i]))
  cat("----------------------------------\n")
}
```

## 작업 수행 후의 컬럼 개수 파악

```{r}
num=c()
for(i in 2:23){
  num=append(num,length(unique(mr[,i])))
}
sum(num)
```

## 별도의 데이터 프레임 생성

```{r}
mr2=data.frame(V1=mr$V1)
head(mr2)
```

```{r}
sort(unique(mr$V2))
```

```{r}
for(i in 2:23){
  for(j in sort(unique(mr[,i]))){
    mr2=cbind(mr2,mr[,i]==j)
  }
}
mr2
```

```{r}
ncol(mr2)
```

```{r}
str(mr2)
```

```{r}
library(dplyr)
```

```{r}
mr2=arrange(mr2,V1) #컬럼 이름 중복으로 인한 에러 발생
```

```{r}
colnames(mr2)=paste("V",1:118,sep="")
head(mr2)
```

## 컬럼 이름과 One-Hot Encoding 한 번에 처리하기

```{r}
mr3=data.frame(V1=mr$V1);head(mr3)
```

```{r}
count=2
for(i in 2:23){
  for(j in sort(unique(mr[,i]))){
    mr3=cbind(mr3,mr[,i]==j)
    colnames(mr3)[count]=paste("V",i,"_",j,sep="")
    count=count+1
  }
}
head(mr3)
```

```{r}
str(mr3)
ncol(mr3)
length(unique(colnames(mr3)))
```

```{r}
mr3=arrange(mr3,V1)
head(mr3)
```

이제 머신러닝을 해보자

```{r}
set.seed(1234)
samp=createDataPartition(mr3$V1,p=0.7,list=F)
data.train=mr3[samp,]
data.test=mr3[-samp,]
x=subset(data.test,select=-V1)
y=data.test$V1
```

```{r}
model.rforest=randomForest(V1~.,data=data.train,ntree=100)
pred.rforest=predict(model.rforest,x,type='class')
mean(pred.rforest==y)
```

```{r}
model.nnet=nnet(V1~.,data=data.train,size=3)
pred.nnet=predict(model.nnet,x,type='class')
mean(pred.nnet==y)
```

```{r}
model.svm=svm(V1~.,data=data.train,size=3)
pred.svm=predict(model.svm,x,type='class')
mean(pred.svm==y)
```
