# Regression

```{r}
regression=read.csv("regression.csv");head(regression)
```

```{r}
str(regression)
```

```{r}
summary(regression$Height)
summary(regression$Weight)
```

```{r}
plot(regression$Height,regression$Weight)
```

```{r}
cor(regression$Height,regression$Weight)
```

```{r}
reg=lm(Weight~Height,data=regression)
plot(regression$Weight~regression$Height)
abline(reg,col="red")
summary(reg)
```

```{r}
paste(reg$coefficients[1]+170*reg$coefficients[2]-6.355,"~",reg$coefficients[1]+170*reg$coefficients[2]+6.355)
```

# IQ

```{r}
iq=read.csv("IQ.csv");head(iq)
```

```{r}
str(iq)
```

### (1) IQ가 126인 사람의 성적 예측

```{r}
iqr=lm(성적~IQ,data=iq)
summary(iqr)
```

```{r}
paste(126*iqr$coefficients[2]-3.322,"~",126*iqr$coefficients[2]+3.322)
```

### (2) 성적과 가장 관련이 깊은 항목은?

```{r}
cor(iq$성적,iq[,-1])
```

### (3) 학원을 몇 군데 다녀야 90점이 될까

```{r}
r=lm(다니는.학원수~성적,data=iq)
summary(r)
```

```{r}
r$coefficients[1]+r$coefficients[2]*90
```

## Multiple Regression

```{r}
data("attitude")
help(attitude)
```

```{r}
head(attitude)
```

```{r}
str(attitude)
```

```{r}
plot(attitude)
```

rating을 제외한 변수들이 rating에 어떤 영향을 미치는지

```{r}
model=lm(rating~.,data=attitude)
summary(model)
```

```{r}
cor(attitude[,1],attitude[,-1])
```

예측력 향상

```{r}
reduced=step(model,direction="backward") #가장 쓸데없는 것부터 제거
```

```{r}
summary(reduced)
```

# Iris에 대한 다중 회귀분석

```{r}
irismodel=lm(as.numeric(Species)~.,data=iris);summary(irismodel)
```

```{r}
reduced=step(irismodel,direction="backward")
```

```{r}
summary(reduced)
```

```{r}
sum(iris[75,-c(5,2)]*reduced$coefficients[-1])+reduced$coefficients[1]-sqrt(deviance(reduced)/reduced$df.residual)
sum(iris[75,-c(5,2)]*reduced$coefficients[-1])+reduced$coefficients[1]+sqrt(deviance(reduced)/reduced$df.residual)
```

```{r}
head(iris)
iris[15,]
```

```{r}
sqrt(deviance(reduced)/reduced$df.residual)
```
