# Simulation

In coin toss simulation we can think about the code that tosses a coin

```{r}
x=runif(1)
if(x<=1/2){
  result=0 #Head
} else{
  result=1 #Tail
}
print(result)
```

But this isn't different from tossing actual coin, so we can use function with loop

```{r}
coin=function(n){
  count1=0 #Head
  count2=0 #Tail
  for(i in 1:n){
    x=runif(1)
    if(x<=1/2){
      count1=count1+1
    } else{
      count2=count2+1
    }
  }
  cat(count1,count2,"\n")
}
```

```{r}
coin(100)
coin(1000)
coin(10000)
```

This is called Monte Carlo Simulation

## Winning chance of RPS

```{r}
rps=function(i){
  #1 for Rock, 2 for Scissors, 3 for Paper
  win=0
  lose=0
  draw=0
  for(n in 1:i){
    man1=sample(1:3,1)
    man2=sample(1:3,1)
    if(man1==man2){
      draw=draw+1
    }else if ((man1==1&man2==3)||(man1==2&man2==1)||(man1==3&man2==2)){
      lose=lose+1
    }else{
      win=win+1
    }
  }
  cat(win,"\t",lose,"\t",draw,"\n")
  cat(round(win/n,2),"\t",round(lose/n,2),"\t\t",round(draw/n,2),"\n")
}
```

```{r}
rps(1000000) #It takes quite long time to see the result
```

## Rolling dice

```{r}
dice=function(n){
  df=rep(0,6)
  
  for(i in 1:n){
    x=sample(1:6,1)
    df[x]=df[x]+1
  }
  
  cat("Throw:",n,"\n")
  for(j in 1:length(df)){
    cat(j,":",df[j],"\n")
  }
  cat("----------------------\n")
}
```

```{r}
options(scipen=100)
dice(10)
dice(100)
dice(1000)
dice(10000)
dice(100000)
```
